import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar.js";
import Footer from "./components/footer.js";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "prøv camping nettside",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Navbar />
      <Footer />
      </body>
    </html>
  );
}

